### ISSUE TITLE
Possible scope issues when enums are involved for openapi to protobuf generation via gnostic-grpc

### ISSUE THREAD

**Issue by nareshbaliga** [jhump/protoreflect#417]
Hello,

I'm using gnostic-grpc to generate a protobuf from my OpenAPI spec. 

I'm running into an issue when enums are involved.

Here is a contrived OpenAPI spec snippet, please note the two occurrences of the attribute _family_:
```yaml {.line-numbers}
components:
  schemas:
    Pet:
      required:
      - id
      - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        family:
          type: string
          enum:
            - dog
            - cat
        detailedFamily:
          type: object
          properties:
            family:
              properties:
                name:
                  type: string
                kind:
                  type: string
                  enum:
                    - dog
                    - cat
```                  

When I run:
`gnostic-grpc --grpc_out=. enum-issue.yml`

I see the following error:
```
panic: interface conversion: desc.Descriptor is *desc.MessageDescriptor, not *desc.EnumDescriptor

goroutine 1 [running]:
github.com/jhump/protoreflect/desc.(*FieldDescriptor).resolve(0xc000440080, 0xc000265828, 0x4, 0x8, 0xc00041d780, 0x2, 0x2, 0x0, 0x0)
	/Users/nbaliga/workspace/protoreflect/desc/descriptor.go:558 +0x79a
github.com/jhump/protoreflect/desc.(*MessageDescriptor).resolve(0xc000425b30, 0xc000265828, 0x3, 0x8, 0xc00041d780, 0x2, 0x2, 0x0, 0x0)
	/Users/nbaliga/workspace/protoreflect/desc/descriptor.go:339 +0x4c5
github.com/jhump/protoreflect/desc.createFileDescriptor(0xc000278e00, 0xc0002f7b60, 0x3, 0x3, 0x0, 0x2, 0xc000265b68, 0xc00034bb60)
	/Users/nbaliga/workspace/protoreflect/desc/convert.go:88 +0x1098
github.com/jhump/protoreflect/desc.createFromSet(0xc000338060, 0x10, 0x0, 0xc00041d690, 0x1, 0x1, 0xc000265b68, 0xc00034bb60, 0xc0001b5960, 0x0, ...)
	/Users/nbaliga/workspace/protoreflect/desc/convert.go:225 +0x358
github.com/jhump/protoreflect/desc.createFileDescriptors(0xc00034bb30, 0x4, 0x6, 0x0, 0x18, 0x1bb9320, 0x0)
	/Users/nbaliga/workspace/protoreflect/desc/convert.go:131 +0x1fd
github.com/jhump/protoreflect/desc.createFileDescriptorsFromSet(0xc000415000, 0x0, 0xc00034bb01, 0xc000415000, 0xc000265db8)
	/Users/nbaliga/workspace/protoreflect/desc/convert.go:193 +0xad
github.com/jhump/protoreflect/desc.createFileDescriptorFromSet(0xc000415000, 0x0, 0x3, 0x4, 0xc00034bb30)
	/Users/nbaliga/workspace/protoreflect/desc/convert.go:169 +0x39
github.com/jhump/protoreflect/desc.CreateFileDescriptorFromSet(...)
	/Users/nbaliga/workspace/protoreflect/desc/convert.go:165
github.com/googleapis/gnostic-grpc/generator.(*Renderer).RenderProto(0xc000306f80, 0xc000415000, 0xc000338050, 0x10, 0xc000338050, 0xc00033805a, 0xc000265e78)
	/Users/nbaliga/workspace/gnostic-grpc/generator/renderer.go:82 +0x49
github.com/googleapis/gnostic-grpc/generator.(*Renderer).Render(0xc000306f80, 0xc00024aaf0, 0xc000338050, 0x10, 0x6, 0xc000338050)
	/Users/nbaliga/workspace/gnostic-grpc/generator/renderer.go:62 +0xac
github.com/googleapis/gnostic-grpc/generator.RunProtoGenerator(0xc00026c420)
	/Users/nbaliga/workspace/gnostic-grpc/generator/main.go:58 +0x33e
main.main()
	/Users/nbaliga/workspace/gnostic-grpc/plugin/main.go:30 +0x145
Errors reading enum-issue.yaml
exit status 2
```

Based on https://github.com/jhump/protoreflect/pull/395/commits/91dd3780b93b830f17e6aba5af3d7a8641595056, I put in some debug statements in the relevant section of the code and I see the following:
```
Plugin error: [could not convert desc name:"Family"  field:{name:"name"  number:1  label:LABEL_OPTIONAL  type:TYPE_STRING  type_name:""}  field:{name:"kind"  number:2  label:LABEL_OPTIONAL  type:TYPE_ENUM  type_name:"Kind"}  enum_type:{name:"Kind"  value:{name:"DOG"  number:0}  value:{name:"CAT"  number:1}} to EnumDescriptor. TypeName: enum_issue.Family. Type: TYPE_ENUM]
```

If I rename either of the _family_ attributes in the spec, there is no issue.

Furthermore, suppose I change the type of of the 1st _family_ attribute to anything other than enum, this also works and there is no issue.

The 2nd occurrence of the _family_ attribute is an object that happens to contain an enum. The 1st occurrence of the _family_ attribute is a straight enum.

And this seems to cause issues.

Any help will be appreciated!

Entire YAML: [enum-issue.txt](https://github.com/jhump/protoreflect/files/7063337/enum-issue.txt)
